---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  ##############################################################################
  ################################ General Checks ##############################
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: .gitignore
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: mkdocs.yml
      - id: check-added-large-files
        args: [--maxkb=1500]
      - id: check-case-conflict
      - id: check-json
        exclude: renovate.json
      - id: check-merge-conflict
      - id: debug-statements
      - id: detect-private-key
  ##############################################################################
  ################################ Security Checks #############################
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        name: Detect secrets
        args:
          - --disable-plugin
          - KeywordDetector
          - --disable-plugin
          - Base64HighEntropyString
          - --exclude-secrets
          - "[0-9a-f]{40}" # commit shas
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.28.0
    hooks:
      - id: gitleaks
  ##############################################################################
  ################################ YAML Checks #################################
  - repo: https://github.com/google/yamlfmt
    rev: v0.17.2
    hooks:
      - id: yamlfmt
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint
##############################################################################
################################ Linting Checks #############################
# - repo: local
#   hooks:
#     - id: prettier
#       name: prettier-local
#       entry: bunx prettier --config .prettierrc.json --check .
#       language: system
#       types: [file]
#       pass_filenames: true
##############################################################################
################################ Shell Checks ################################
# - repo: https://github.com/gruntwork-io/pre-commit
#   rev: v0.1.24
#   hooks:
#     - id: shellcheck
